# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)

tasks:
  - init: pnpm install
    command: pnpm dev

ports:
  - name: Website
    description: Opens website in browser
    port: 3000
    onOpen: open-browser
